[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-tau-model"
version = "1.0.0"
authors = [
  { name = "Joosep Pata", email = "joosep.pata@cern.ch" },
]
description = "Machine Learning models for Tau reconstruction"
readme = "README.md"
requires-python = "==3.11.*"
license = { text = "Apache Software License" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "awkward",
    "boost-histogram",
    "hydra-core",
    "lightning",
    "matplotlib",
    "mplhep",
    "numpy",
    "omegaconf",
    "pandas",
    "psutil",
    "pyarrow",
    "scikit-learn",
    "scipy",
    "tensorboard",
    "torch",
    "torchvision",
    "tqdm",
    "vector",
]

[project.scripts]
mltau-train = "mltau.scripts.train:train"
mltau-plot-roc = "mltau.scripts.plot_roc:plot_roc"

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["tests*", "notebooks*", "images*", "docs*", "scripts*"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]
