training:
  debug_run: False
  lr: 0.001
  model:
    name: MultiParTau  # MultiParTau | SingleParTau
    task: is_tau       # SingleParTau only: is_tau | charge | decay_mode | kinematics
  trainer:
    max_epochs: 100

  task_weights:
    tau_id: 1.0
    charge: 1.0
    decay_mode: 1.0
    kinematics: 1.0

  dataloader:
    batch_size: 8192
    num_dataloader_workers: 8
    prefetch_factor: 2
